image: php:8.0

pipelines:
  default:
    - step:
        name: Deploy staging
        deployment: staging
        script:
          - apt-get update && apt-get install -y libssh2-1-dev git unzip
          - git clone https://github.com/php/pecl-networking-ssh2.git /usr/src/php/ext/ssh2 && docker-php-ext-install ssh2
          - ./deployer.phar deploy 51.159.18.14
